
script: 
 - "/usr/bin/xmllint /home/travis/build/Javauto/javauto-notepad-plusplus/userDefineLang_Javauto.xml"
 - "/usr/bin/xmllint /home/travis/build/Javauto/javauto-notepad-plusplus/javauto.xml"
 
sudo: false
